### ISSUE TITLE
Add babashka tasks to run mock sequencer

### ISSUE THREAD

**Issue by jannikluhn** [shutter-network/rolling-shutter#224]
- deploy and configure necessary contracts
- run L2geth

**Comment by ezdac** [comment]
The scope of this changed now, since we are using our own (non-optimism) related mock-sequencer.

The mock-sequencer needs to be run and configured from the babashka play tasks.

- [ ] adapt the mock sequencers CLI options to use a config file (similar to other `rolling-shutter` subcommands)
- add babashka tasks similar to existing subcommand tasks:
  - [ ] `mocksequencer-subcommand` tasks
  - [ ] `genconfig:mocksequencer` configuration-file creation task
  
  
Related: #343

**Comment by ezdac** [comment]
Closed as of https://github.com/shutter-network/rolling-shutter/pull/344
